### ISSUE TITLE
The link for the VGG-Flower dataset is invalid

### ISSUE THREAD

**Issue by lidongyue12138** [henrygouk/mars-finetuning#1]
I am trying to reproduce the results from the paper. 

- I find the link provided in this repo for the VGG-Flower dataset is invalid. Could you provide a valid link to download the data?
- There are several other datasets used in the paper. Could you provide a way to prepare these data for this code?

Thanks for your attention!

**Comment by henrygouk** [comment]
Sorry, the link should be fixed now.

Yes, I think just adding scripts to convert from the default dataset formats into something useable by the code in this repo is probably a better long term solution than just hosting all the prepared data myself. I'll hopefully be able to update the repo with these scripts over the next couple of days.
